### ISSUE TITLE
Resetting the picked files.

### ISSUE THREAD

**Issue by drinikol** [Jaaneek/useFilePicker#12]
Is there a way to reset the files chosen after submitting a form?

**Comment by Jaaneek** [comment]
We will do that in the future, any pull requests are open. Im thinking about clear() function

**Comment by drinikol** [comment]
> We will do that in the future, any pull requests are open. Im thinking about clear() function

That would be great! looking forward to it in the future! And thank you for this wonderful package.

**Comment by Jaaneek** [comment]
Done, good job. I had to make only few linting fixes. I will commit them right away.
Thank you a lot!
