### ISSUE TITLE
ESM Dist files have different name than package.json

### ISSUE THREAD

**Issue by gustavorino** [Jaaneek/useFilePicker#13]
I'm using VITE bundler and I am getting import errors :

The module entry on package.json is :

```json
{
"module": "dist/usefilepicker.esm.js",
}
```

however the build file is 
<img width="293" alt="Screen Shot 2021-05-07 at 08 35 41" src="https://user-images.githubusercontent.com/4224712/117444006-43b15f00-af0f-11eb-8fe6-cd8779a18453.png">

For now, I'm importing directly from /dist/use-file-picker.esm.js which solves the issue, but It would be nice to fix it

**Comment by MrKampla** [comment]
I've investigated the issue and as You said, it seems like it just needs the module entry change. We'll fix this soon.

**Comment by MrKampla** [comment]
We've just released new version 1.1.2 which incorporates the solution to the issue mentioned above. Everything should be working correctly right now.
