### ISSUE TITLE
ImageDims not triggering errors. 

### ISSUE THREAD

**Issue by drinikol** [Jaaneek/useFilePicker#20]
I tried setting up a limit for the thumbnail image but it doesn't throw and error. Error array is always empty even uploading different dimensions of image. Am I doing something wrong or this is a bug? Thank you!
`   const [
        openFileSelectorThumbnail,
        thumbnailData
    ] = useFilePicker({
        multiple: false,
        readAs: "DataURL", 
        accept: [".jpg", ".jpeg"],
        maxImageHeight: 720, 
        minImageHeight: 720,
        maxImageWidth: 1280,
        minImageWidth: 1280
    });`

**Comment by Jaaneek** [comment]
fixed in https://github.com/Jaaneek/useFilePicker/pull/19
