### ISSUE TITLE
Remove an index instead of clearing the whole thing

### ISSUE THREAD

**Issue by hhemmati81** [Jaaneek/useFilePicker#26]
Is there a way to remove just one file at a certain index rather than clearing the whole list?

**Comment by MrKampla** [comment]
Hi @hhemmati81,
Currently, there is no way to do that directly. But You can create Your own state and modify it accordingly to the list returned from the hook by Yourself. Please take a look at that example:
https://codesandbox.io/s/dreamy-hamilton-n4r2r?file=/src/App.js

Let us know if this is a sufficient solution to Your problem.

**Comment by hhemmati81** [comment]
This solution works great thanks!
