### ISSUE TITLE
Add events (e.g. onChange, onError)?

### ISSUE THREAD

**Issue by stephanbogner** [Jaaneek/useFilePicker#32]
I am actually not sure if this is possible, since we have a hook approach here, but my question is:

**How easy (or possible) would it be to have onError-event or an onChange-event that has loading/error states?**
(Happy to make a contribute if pointed in the right direction)

**Use case:**
- I have my normal button component which I attach the hook too (which is why this library is perfect 👍 ) 
- After the user has chosen a file throws an error I want to show a toast containing the relevant error
- → Currently I have to manually check whether the _errors_ variable has changed so I only trigger the toast once

It's not a big deal but would be really comfortable to have events for this kind of use case.

**Comment by stephanbogner** [comment]
**FYI: This is how I currently handle the problem:**

```
import React, { useState } from "react";
import { useFilePicker } from 'use-file-picker';

export default function CoverPhoto(props) {
  const [imageErrors, setImageErrors] = useState([]);

  const [openFileSelector, { filesContent, loading, errors }] = useFilePicker({
    readAs: 'DataURL',
    accept: 'image/*',
    multiple: false,
    limitFilesConfig: { max: 1 },
    maxFileSize: 12
  });

  if(JSON.stringify(errors) !== JSON.stringify(imageErrors)){
    setImageErrors(errors);
    if(errors.length > 0){ console.log('Trigger Toast now') }
  }

  return (
    <div>
      <button idle={loadingImage} onClick={openFileSelector}>Choose photo</button>
      { filesContent.length > 0 ? (<img alt={filesContent[0].name} src={filesContent[0].content}></img>) : null }
    </div>
  )
}
```

**Comment by stephanbogner** [comment]
I ended up writing a custom solution, because use-file-picker somehow didn't work well with [Supabase](https://supabase.com/docs/guides/with-react#create-an-upload-widget).

Maybe the files response from the hook is too different from the standard one? I honestly couldn't figure it out 🤷

**Comment by MrKampla** [comment]
@stephanbogner What do You mean by"'not working well with Supabase"? Supabase upload function accepts [File](https://developer.mozilla.org/en-US/docs/Web/API/File) type JS object and useFilePicker returns `files` objects that are fulfilling the contract of File type, so everything should work the same as if files were fetched from plain input element.

**Comment by bewithme** [comment]
how to get abs file path ?

**Comment by MrKampla** [comment]
@bewithme Unfortunately, there is no way of getting paths for selected files because browsers don't allow to get them due to security reasons.

**Comment by stephanbogner** [comment]
> @stephanbogner What do You mean by "not working well with Supabase"? Supabase upload function accepts [File](https://developer.mozilla.org/en-US/docs/Web/API/File) type JS object and useFilePicker returns `files` objects that are fulfilling the contract of File type, so everything should work the same as if files were fetched from plain input element.

Yeah, I don't fully understand it myself ... because I thought the same thing.

**I just checked the response through useFilePicker vs native and it differs a bit:**
useFilePicker already contains the _content_, but lacks _lastModifiedDate_, _size_, _type_ and _webkitRelativePath_. 
Maybe Supabase checks for those properties and maybe one/multiple of those cause the issue (my guess would be the lack of _type_ but I have not checked).

<img width="839" alt="Screenshot 2022-01-10 at 14 36 54" src="https://user-images.githubusercontent.com/7897006/148775393-bd067fa4-5ad6-444e-95d4-33cb6049fec5.png">

<details>
<summary>The code I used to check this:</summary>

```
import React, {useRef} from 'react';
import { useFilePicker } from 'use-file-picker';

export default function App() {
  const hiddenFileInput = useRef(null);
  const [openFileSelector, { filesContent, loading }] = useFilePicker({
    accept: '*',
  });
  
  const triggerFileInput = event => {
    hiddenFileInput.current.click();
  };

  const onFileSelect = event => {
    console.log('### Via Native:');
    console.log(event.target.files)
  }

  console.log('### Via useFilePicker:');
  console.log(filesContent)

  return (
    <div>
      <button onClick={() => openFileSelector()}>
        Select files (useFilePicker)
      </button>

      <input
          multiple
          ref={hiddenFileInput}
          style={{display: "none"}}
          type="file"
          onChange={onFileSelect}
        />
      <br/>
      <button  onClick={triggerFileInput}>
        Select files (native)
      </button>
    </div>
  );
}
```

</details>

**Comment by chris-aeviator** [comment]
> 
Isn't this completely bypassing useFilePicker alltogether??

**Comment by stephanbogner** [comment]
> @stephanbogner
> 
> Isn't this completely bypassing useFilePicker altogether??

It's a comparison between the data returned from the native file picker vs. useFilePicker. I posted both outputs.

Or what do you mean?

**Comment by chris-aeviator** [comment]
I'm trying to `useEffect` at the moment, which triggers on `loading` changes, but will still not have the files. I try to get to the `onChange` model, but with the originial useFilePicker functionality

**Comment by stephanbogner** [comment]
@chris-aeviator Ah, I see. I can't help you there unfortunately.

But it sounds like the reason why I originally opened this issue ... except then everybody focussed on the Supabase bit 😄 .
In the end I went custom, because then you can use the regular onChange listeners.

<details>
<summary>
Extraction from my code if it helps you:
</summary>

```
import React, { useState, useRef } from "react";

export default function Comp(props) {
    const maxFileSize = props.maxFileSize || 12;
    const hiddenFileInput = React.useRef(null);
    const [imageLoading, setImageLoading] = useState(false);
    const [imageSrc, setImageSrc] = useState(null);

    const onImageSelect = async (event) => {
        // Only works for 1 image for now
        let errors = [];
        if(!event.target.files || event.target.files.length === 0){
          errors.push('no-image-selected');
        }else{
          let firstImage = event.target.files[0];
          const sizeInMb = Math.ceil(firstImage.size / 1000000 * 10) / 10;
          if(sizeInMb > maxFileSize){
            errors.push('file-too-large');
          }else{
            setImageLoading(true);
            let reader = new FileReader();
            reader.onloadend = () => {
                setImageSrc(reader.result)
                setImageLoading(false);
            }
            reader.readAsDataURL(firstImage);
          }
        }

        if(errors){
            //showToast(errors)
        }
    }

    const triggerFileInput = event => {
        hiddenFileInput.current.click();
    };

    const handleClear = () => {
        setImageSrc(null);
        hiddenFileInput.current.value = null;
    }

    return (
        <div>
            <input
                  ref={hiddenFileInput}
                  className="hidden"
                  type="file"
                  accept="image/*"
                  onChange={onImageSelect}
                />

            <button onClick={triggerFileInput}>
                Choose image
            </button>

            <button onClick={handleClear}>
                Clear image
            </button>

            <div>
                Image is loading: {String(imageLoading)}
            </div>

            <img src={imageSrc}/>
        </div>)
}
```
</details>

**Comment by MrKampla** [comment]
> > @stephanbogner What do You mean by "not working well with Supabase"? Supabase upload function accepts [File](https://developer.mozilla.org/en-US/docs/Web/API/File) type JS object and useFilePicker returns `files` objects that are fulfilling the contract of File type, so everything should work the same as if files were fetched from plain input element.
> 
> @MrKampla Yeah, I don't fully understand it myself ... because I thought the same thing.
> 
> **I just checked the response through useFilePicker vs native and it differs a bit:** useFilePicker already contains the _content_, but lacks _lastModifiedDate_, _size_, _type_ and _webkitRelativePath_. Maybe Supabase checks for those properties and maybe one/multiple of those cause the issue (my guess would be the lack of _type_ but I have not checked).
> 
> <img alt="Screenshot 2022-01-10 at 14 36 54" width="839" src="https://user-images.githubusercontent.com/7897006/148775393-bd067fa4-5ad6-444e-95d4-33cb6049fec5.png">
> 
> The code I used to check this:

@stephanbogner  As far as I know, _lastModifiedDate_ and _webkitRelativePath_ are non-standard properties that are added only by chrome and Firefox but missing _size_ and _type_ properties may be the reason behind not working correctly with Supabase. We'll have to investigate that and if that's the case, we'll change the return interface to match File API specification.

**Comment by MrKampla** [comment]
> I'm trying to `useEffect` at the moment, which triggers on `loading` changes, but will still not have the files. I try to get to the `onChange` model, but with the originial useFilePicker functionality.
> 
> ok, this seems to be working actually
> 
> ```
>   useEffect(() => {
>     if (filesContent.length > 0) {
>       setUserHasUploadedFile(true)
>     }
>   }, [filesContent])
> ```

Exactly, that's the way that we, useFilePicker maintainers, prefer to react to file changes. And we strongly encourage all our users to use this technique too. OnChange handler function seems redundant in our package, as we can achieve the same functionality with useEffect hook.

**Comment by chris-aeviator** [comment]
@MrKampla ok :+1:  - I think it would be useful then to add it to the docs

**Comment by MrKampla** [comment]
> @chris-aeviator Ah, I see. I can't help you there unfortunately.
> 
> But it sounds like the reason why I originally opened this issue ... except then everybody focussed on the Supabase bit 😄 . In the end I went custom, because then you can use the regular onChange listeners.
> 
> Extraction from my code if it helps you:
> ```
> import React, { useState, useRef } from "react";
> 
> export default function Comp(props) {
>     const maxFileSize = props.maxFileSize || 12;
>     const hiddenFileInput = React.useRef(null);
>     const [imageLoading, setImageLoading] = useState(false);
>     const [imageSrc, setImageSrc] = useState(null);
> 
>     const onImageSelect = async (event) => {
>         // Only works for 1 image for now
>         let errors = [];
>         if(!event.target.files || event.target.files.length === 0){
>           errors.push('no-image-selected');
>         }else{
>           let firstImage = event.target.files[0];
>           const sizeInMb = Math.ceil(firstImage.size / 1000000 * 10) / 10;
>           if(sizeInMb > maxFileSize){
>             errors.push('file-too-large');
>           }else{
>             setImageLoading(true);
>             let reader = new FileReader();
>             reader.onloadend = () => {
>                 setImageSrc(reader.result)
>                 setImageLoading(false);
>             }
>             reader.readAsDataURL(firstImage);
>           }
>         }
> 
>         if(errors){
>             //showToast(errors)
>         }
>     }
> 
>     const triggerFileInput = event => {
>         hiddenFileInput.current.click();
>     };
> 
>     const handleClear = () => {
>         setImageSrc(null);
>         hiddenFileInput.current.value = null;
>     }
> 
>     return (
>         <div>
>             <input
>                   ref={hiddenFileInput}
>                   className="hidden"
>                   type="file"
>                   accept="image/*"
>                   onChange={onImageSelect}
>                 />
> 
>             <button onClick={triggerFileInput}>
>                 Choose image
>             </button>
> 
>             <button onClick={handleClear}>
>                 Clear image
>             </button>
> 
>             <div>
>                 Image is loading: {String(imageLoading)}
>             </div>
> 
>             <img src={imageSrc}/>
>         </div>)
> }
> ```

And why do You need the onChange handler? The code You've posted there can be written with useFilePicker and useEffect. For validation, You can use the Validator functionality built into useFilePicker: https://github.com/Jaaneek/useFilePicker/blob/master/README.md#custom-validation

**Comment by MrKampla** [comment]
> @MrKampla ok 👍 - I think it would be useful then to add it to the docs

Good catch, will do! Thanks for Your input 👍

**Comment by stephanbogner** [comment]
@MrKampla 
> And why do You need the onChange handler? The code You've posted there can be written with useFilePicker and useEffect. For validation, You can use the Validator functionality built into useFilePicker: https://github.com/Jaaneek/useFilePicker/blob/master/README.md#custom-validation

Maybe it's personal preference but I don't see the advantage of using hooks for everything, when a simple event listener does the job too. In my experience having too much abstraction is gonna cause issues eventually.

But feel free to close the issue since you mentioned using hooks is the recommended approach 👍

**Comment by MrKampla** [comment]
@stephanbogner The advantage of using hooks is brevity, readability and unification. The React dev team stated that hooks are the future of React, and we want to stick to the standards. Code just becomes more pleasant to read for React developers if You use common solutions. From the way You write about hooks, I assume that React is not Your first framework, and You were doing websites with another language before or at least with plain JS. There's nothing wrong about it - of course You can have Your personal preference but we, as maintainers of open source package, have to stick to some guidelines.
I'm closing this issue now with the following bullet points:
- check if useFilePicker works with Supabase, if not then change return File type to match default browser File API specification
- add new section to docs about hooks being recommended approach of listening for file changes 

Thank You all for Your input!
