### ISSUE TITLE
Is there a way to control the file picker options

### ISSUE THREAD

**Issue by RuzenDev** [Jaaneek/useFilePicker#38]
I dont want the options to be shown to pick the image from camera or folder. is it possible. if so please guide me

![Screenshot_20220509-150045](https://user-images.githubusercontent.com/92197420/167349700-e96f0540-817e-4b5b-8431-ba8e290c775d.png)

**Comment by RuzenDev** [comment]
I am aware of this 

https://codesandbox.io/s/busy-nightingale-oox7z?file=/src/App.js

but it doesnt work in ios

**Comment by MrKampla** [comment]
As far as I know, that's a default browser behaviour and there is no way to change it.

What do You mean by "it doesn't work in iOS"? We've tested the hook on multiple operating systems (including iOS) and everything works as expected. Could You elaborate on Your issue with iOS?

**Comment by RuzenDev** [comment]
@MrKampla Thank you very much for your reply. 

I see. So it's the browser behavior right?

I actually meant, in Android when i only try to get image from the gallery of the device following the codes in 
https://codesandbox.io/s/busy-nightingale-oox7z?file=/src/App.js ,
it really works well. 

However in iOS, it shows up the popover menu options including camera. So, according to you its impossible in iOS to open the gallery directly because it's due to iOS browser behavior.  Am I correct?

**Comment by MrKampla** [comment]
@RuzenDev yes, it's impossible as it's a default iOS behavior, and we can't change it. Technically, the browser doesn't want to restrict users to only pick images from the gallery because a user can have some images stored in different directories.

**Comment by RuzenDev** [comment]
@MrKampla Thank you so much. I understand it. 

Thanks for your great library.
