### ISSUE TITLE
Renders Twice

### ISSUE THREAD

**Issue by Kenneth-Fernandes-0620** [Jaaneek/useFilePicker#40]
This Custom Hook renders the component it is used in 'twice'

![useFilePicker Custom Hook Multiple Render](https://user-images.githubusercontent.com/57480946/174429372-19f817a9-ce78-4b33-9de7-72910aab6c5d.png)

Above is a screenshot of the **Simple txt file content reading** usage example in codesandbox. 
We can see that by just adding a console statement that the Component using the hooks is rendering twice

**Comment by Jaaneek** [comment]
I cant check it right now but I will give my opinion.

1. Isnt this related to react strictmode, when we are using that every component will be rendered twice at mount to detect memory leaks and other side effects faster.
2. Even if it is rendering the component twice, is that a problem? Can you elaborate why should we avoid it? React usually does a lot of unnecessary rerenders and common approach is to optimise it only when something is lagging.

**Comment by Kenneth-Fernandes-0620** [comment]
Thanks a lot @Jaaneek , yes this issue was related to The Strict Mode in React
