### ISSUE TITLE
File size validation is bugged for multiple file select in latest version

### ISSUE THREAD

**Issue by ls-sergey-uss** [Jaaneek/useFilePicker#46]
When selecting multiple files it would appear that only the first one is validated for size.
Im attaching a demo where if I select a file exceeding maxFileSize its not added to plainFiles and error is produced. However if my first file in multi selection is smaller than maxFileSize the whole bunch is added and no error is produced.

[Sandbox](https://codesandbox.io/s/magical-perlman-et40cx?file=/src/App.js:251-262) 
## Demo
https://user-images.githubusercontent.com/77397783/181311011-5213edfa-ad02-403a-a64b-6dbfd61b67f0.mov

**Comment by ls-sergey-uss** [comment]
Perhaps worth mentioning that version 1.0.0 doesnt appear to have this issue.

**Comment by Jaaneek** [comment]
Thanks for reporting it, I can check it in few days, maybe someone else can take a look @MrKampla @GitKokoszka.

**Comment by MrKampla** [comment]
Yesterday, we released version 1.5.1 containing a fix for this issue. Closing the thread.
