### ISSUE TITLE
Not working in mobile Safari for option media library and take a foto

### ISSUE THREAD

**Issue by Yu-vo** [Jaaneek/useFilePicker#48]
When I try to load a photo using option the media library or camera in Safari mobile, nothing happens.
If use option Choose file, it is ok

**Comment by Yu-vo** [comment]
need add 
document.body.appendChild(inputElement);
into openFileDialog

**Comment by Jaaneek** [comment]
Which version are you at? Are you sure its the latest?

**Comment by Yu-vo** [comment]
It's really in the version thanks

**Comment by Jaaneek** [comment]
You are welcome!
