### ISSUE TITLE
Content Security Policy error

### ISSUE THREAD

**Issue by WhistlingZephyr** [Jaaneek/useFilePicker#53]
Hello! I encountered a previously closed issue, https://github.com/Jaaneek/useFilePicker/issues/33.
![image](https://user-images.githubusercontent.com/90854121/213637730-19ce7086-e934-488c-89ff-82f2c2926f10.png)
Upon inspection, I found that it's from a dependency of this package:
![image](https://user-images.githubusercontent.com/90854121/213637823-87e39bc6-010b-4021-9b30-fa2f47a5e368.png)
Searching up the code, I found that it's originally from [regenerator-runtime](https://github.com/facebook/regenerator/blob/c24b7b7259ee8a6cea192c220860cc81bafb4571/packages/runtime/runtime.js#L759) which is a dependency of [@babel/plugin-transform-regenerator](https://github.com/babel/babel/blob/0f68471ef79933e192b69f2ebdf586fb5d5e54ce/packages/babel-plugin-transform-regenerator/package.json#L15) which is used by [@babel/preset-env](https://github.com/babel/babel/blob/main/packages/babel-preset-env/package.json#L78).

I searched up on how to disable it and came across https://stackoverflow.com/a/45729942 which tells to use
```json
{
   "presets": [
      ["env", {
         "exclude": ["transform-regenerator"]
      }]
   ]
}
```
to disable it. However, that left me with
```
(babel plugin) Error: Cannot find module 'babel-preset-env'
- Did you mean "@babel/env"?
```
and upon searching that up, I came across https://stackoverflow.com/a/56519488 which tells to use `@babel/preset-env` instead of `env`. And that fixed the issue.

Since this project doesn't directly use babel and instead uses tsdx, the issue was tsdx transpiling with [transform-regenerator explicitly enabled](https://github.com/jaredpalmer/tsdx/blob/master/src/babelPluginTsdx.ts#L79), and since it allows [overriding the babel config](https://tsdx.io/customization#babel), that can be used to exclude said poly-fill.

In terms of compatibility, regenerator-runtime is rarely needed these days[^1][^2][^3]. So I'm hoping that won't be a problem.

I've implemented the changes in my fork https://github.com/WhistlingZephyr/useFilePicker which seems to not give said error anymore. I'll be sending a PR for it shortly. Thanks!

[^1]: https://github.com/vercel/next.js/discussions/15381
[^2]: https://caniuse.com/async-functions
[^3]: https://caniuse.com/mdn-javascript_functions_method_definitions_async_generator_methods

**Comment by MrKampla** [comment]
Hey @WhistlingZephyr
Great stuff! We really appreciate the amount of work you put in to come up with such a comprehensive explanation and a solution. I wish every issue was described this way ;)

Your solution looks fine, I'll review and merge your PR shortly.

**Comment by MrKampla** [comment]
@WhistlingZephyr Your PR has been merged! Thank you again for your input. The new change has been shipped to NPM with a new version of use-file-picker@1.5.2
