### ISSUE TITLE
Just need onChange

### ISSUE THREAD

**Issue by fabpico** [Jaaneek/useFilePicker#57]
I need more control over the state of the chosen files. I already had this situation https://github.com/Jaaneek/useFilePicker/issues/26 and fixed it also with `useEffect`.

```js
    const [openFileSelector, {filesContent}] = useFilePicker({
        accept: props.fileEndings,
        multiple: Boolean(props.multiple),
        readAs: 'DataURL',
    });

    useEffect(() => {
        props.onChange(filesContent)
    }, [filesContent])
```
But now I want to repopulate a file selection in an edit form. But `useEffect` will overwrite anything with an empty `filesContent` due to its initializaiton.

Can there not just be an onChange within `useFilePicker` to use?

**Comment by MrKampla** [comment]
What do you mean by "repopulate a file selection"? Do you want to keep the previous selection or just avoid the onChange invocation with empty array?  Here are some solutions:
- for keeping previous selection: https://github.com/Jaaneek/useFilePicker/issues/51#issuecomment-1262184562
- If you want to avoid the initialization step, then just add an if statement to your useEffect:
```js
useEffect(() => {
  if (filesContent.length) {
    props.onChange(filesContent)
  }
}, [filesContent])
```
With that check, your onChange won't be called without actual content. 

> Can there not just be an onChange within `useFilePicker` to use?

We believe it's not needed. You can read more about reasons here: https://github.com/Jaaneek/useFilePicker/issues/32#issuecomment-1010894551

**Comment by MrKampla** [comment]
Ok, we'll talk through it within the maintainers team. Thanks for the suggestion. 

It is also worth noting that we're currently in the process of changing the openFileSelector function to return a promise with all the values returned from the hook, which was suggested here #56 and is currently in code review #58. We'll be releasing version 1.6.0 with that feature soon, so maybe you can use it before we implement onChange.

**Comment by MrKampla** [comment]
Turns out that we weren't able to reliably introduce promise to useFilePicker due to browser APIs, more explanation can be found here: https://github.com/Jaaneek/useFilePicker/pull/58#issuecomment-1496680066
Because of that, we decided to implement onChange handlers like you suggested @fabpico.
There is already a PR for this: #60 and we're aiming to bring this feature in the next release 1.6.0.

Thanks for your input @fabpico!

**Comment by Jaaneek** [comment]
We had to do quick bump to 1.6.1, let us know if we can close this issue once you test it out @fabpico

**Comment by fabpico** [comment]
@Jaaneek How to use it?

**Comment by MrKampla** [comment]
@fabpico just pass handlers as props to the hook.
There are 3 functions you can use, which are described in the docs:
<img width="833" alt="image" src="https://user-images.githubusercontent.com/46401284/231471961-26c90c15-214c-4b99-a29d-1055bd6edc63.png">

example:
```ts
const [openFilePicker] = useFilePicker({
   onFilesSelected: (data) => { 
      // your logic whenever user submits valid or invalid files
   },
})
```

**Comment by fabpico** [comment]
Works so far 👍 . Thanks for the quick feedback and improvement.
