### ISSUE TITLE
Support for Node.js 18

### ISSUE THREAD

**Issue by marcusforsberg** [Jaaneek/useFilePicker#64]
Hi! With the release of 1.6.0, support for Node.js 18 [was dropped](https://github.com/Jaaneek/useFilePicker/commit/6720a3832034b007bf100993f18b706265029942#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R54). Is there any particular reason for this? I was waiting for the onFilesSelected callback for my project but since I'm using Node.js 18 I'm not able to install the latest version.

**Comment by Jaaneek** [comment]
@marcusforsberg fix incoming, sorry!

**Comment by Jaaneek** [comment]
@marcusforsberg Should be good now on 1.6.1

**Comment by marcusforsberg** [comment]
Thanks @Jaaneek, works like a charm! 😊
