### ISSUE TITLE
`FileContent.contents` type is incorrect

### ISSUE THREAD

**Issue by japraj** [Jaaneek/useFilePicker#70]
Hello when the `readAs` option is passed to `useFilePicker` as e.g. `"ArrayBuffer"`, the type of `FileContent.contents` is `ArrayBuffer` but in the documentation and type definitions, the type of contents is just `string` which is incorrect

**Comment by MrKampla** [comment]
Hi,
This is going to be fixed in V2, which should be released in a few days. You can track progress on this release here #73

**Comment by MrKampla** [comment]
Closing this issue as it was fixed in 2.0.0 release.
