### ISSUE TITLE
Typo in onFilesSuccessfulySelected callback

### ISSUE THREAD

**Issue by chriswilty** [Jaaneek/useFilePicker#74]
Should be onFilesSuccessfullySelected.

**Comment by MrKampla** [comment]
Marking as duplicate as it was already reported here: #72 
A fix for this will be included in the next 2.0.0 release that should be shipped within a few days, you can track progress here: #73

**Comment by MrKampla** [comment]
Closing this issue as it was fixed in 2.0.0 release.
