### ISSUE TITLE
FileSizeValidator example is broken

### ISSUE THREAD

**Issue by cellis** [Jaaneek/useFilePicker#77]
Just tested this and I believe the `maxFileSize` and `minFileSize` should be given in bytes, like this:

```
new FileSizeValidator({
        maxFileSize: 10 * 1024 * 1024, // 10MB
      }),
```

And thanks, it's a great library!

**Comment by MrKampla** [comment]
Hi @cellis,
You're right, thanks for spotting the mistake. I've just created a PR to fix it, It'll be merged shortly.
Glad that you like our library!
