### ISSUE TITLE
Issue with `clear` Function in `useImperativeFilePicker` Not Clearing `filesContent`

### ISSUE THREAD

**Issue by talkingdonkeyz** [Jaaneek/useFilePicker#82]
### Description
I am experiencing an issue with the `useImperativeFilePicker` hook from the `use-file-picker` library where calling the `clear` function does not clear the `filesContent` as expected. This issue is hindering the functionality of my application as I am unable to reset the file picker to its initial state.

### Steps to Reproduce
1. Open the provided CodeSandbox link: [CodeSandbox Example](https://codesandbox.io/s/wizardly-goldwasser-lgpvrn)
2. Use the "Select File" button to choose a file.
3. Observe the selected file's name displayed on the screen.
4. Use the "Clear Files" button in an attempt to clear the selected file.
5. Notice that the file content is still displayed, indicating that `filesContent` has not been cleared. It is however cleared from `plainFiles`

### Expected Behavior
Upon clicking the "Clear Files" button, I expect the `filesContent` to be cleared and the displayed file content to be removed from the screen, resetting the file picker to its initial state.

### Observed Behavior
After clicking the "Clear Files" button, the `filesContent` remains unchanged and the file content is still displayed on the screen.

**Comment by MrKampla** [comment]
Hey @talkingdonkeyz, thanks for reporting the issue.
It turned out to be a one-liner fix, I've just released a canary version `2.1.1-canary.0` which you can use right now in order to continue working on your project. Once the PR gets the proper approval, I'll release an official version of 2.1.1.

So for now please use:
```
npm install use-file-picker@2.1.1-canary.0
```

I'll add a comment here once the PR gets merged.

**Comment by MrKampla** [comment]
v2.1.1 was officially released, so you don't have to use the canary release
