### ISSUE TITLE
Not able to open file selector

### ISSUE THREAD

**Issue by vinodhum** [Jaaneek/useFilePicker#90]
Hi I am getting below error, how to fix it ?

`TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them at Function.invokeGetter (<anonymous>:3:28)`

```import { useFilePicker } from 'use-file-picker';
import React from 'react';

export default function App() {
  const { openFilePicker, filesContent, loading } = useFilePicker({
    accept: '.txt',
  });

  if (loading) {
    return <div>Loading...</div>;
  }

  return (
    <div>
      <button onClick={() => openFilePicker()}>Select files</button>
      <br />
      {filesContent.map((file, index) => (
        <div>
          <h2>{file.name}</h2>
          <div key={index}>{file.content}</div>
          <br />
        </div>
      ))}
    </div>
  );
}```

**Comment by Jaaneek** [comment]
Can you create a codesanbox reproduction?

**Comment by vinodhum** [comment]
here is stackblitz https://stackblitz.com/edit/vitejs-vite-z79xzc?file=src%2FApp.jsx

**Comment by Jaaneek** [comment]
@vinodhum Which browser and Operating system are you using? This works perfectly for me 🥲

**Comment by vinodhum** [comment]
looks like it was problem with chrome, after your comment I tried it on brave it worked fine. So, I updated chrome and it started working, thanx @Jaaneek
